### ISSUE TITLE
Where the cathegroienames coming from?

### ISSUE THREAD

**Issue by CloudeLecaw** [SuperRonanCraft/AdvancedModreq#14]
![image](https://user-images.githubusercontent.com/12080017/46534657-30e2d380-c8a9-11e8-8bb0-f84717525194.png)

menue.yml:
```
  Manual:
  - Griefing:
      Name: '&c&lGriefing'
      Lore:
      - ''
      - '&7SSetzt die Ticketkathegorie auf &cGriefing'
      Slot: 3
  - Anderes:
      Name: '&c&lAnderes'
      Lore:
      - ''
      - '&7SSetzt die Ticketkathegorie auf &cAndere'
      Slot: 5
```
config:
```
Category:
  Enabled: true
  Categories:
    Griefing:
      Description:
      - '&6Anderes &f- &7mache einen Report für alle anderen Dinge'
      Importance: 5
      Item: tnt
    Anderes:
      Description:
      - '&6Anderes &f- &7mache einen Report für alle anderen Dinge'
      Importance: 0
      Item: anvil
```

**Comment by SuperRonanCraft** [comment]
In the config.yml you need to change the format to this
```
Category:
  Enabled: true
  Categories:
    - Griefing:
        Description:
        - '&6Anderes &f- &7mache einen Report für alle anderen Dinge'
        Importance: 5
        Item: tnt
    - Anderes:
        Description:
        - '&6Anderes &f- &7mache einen Report für alle anderen Dinge'
        Importance: 0
        Item: anvil
```
In the menu.yml, the categories name MUST be the same as in the config.yml, I might be changing the way these categories work a little in the next patch to remove confusion
