### ISSUE TITLE
Problem with deleting categories

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [SuperRonanCraft/AdvancedModreq#8]
Hi,
Im using paperspigot 1.13.1 and when I'm deleting categories: Griefing and Others, they are still appearing in my gui on creating tickets.

Also, when I try to /modreq close 1 Something it says, that usage is.. and works only when I dont type message, so tickets are not flagged as resolved :/

**Comment by CloudeLecaw** [comment]
**in menu.yml:**
i can agree this

Before:
```
  Manual:
    Griefing:
      Name: '&c&lGriefing'
      Lore:
      - ''
      - '&7SSetzt die Ticketkathegorie auf &cGriefing'
      Slot: 4
    Anderes:
      Name: '&c&lAnderes'
      Lore:
      - ''
      - '&7SSetzt die Ticketkathegorie auf &cAndere'
      Slot: 6
```
afer reloading:
```
Category:
  Enabled: true
  Categories:
    Griefing:
      Description:
      - '&6&m------&r &6&lReportsystem &8| &7Kathegorien &6&m------'
      Importance: 5
      Item: tnt
    Other:
      Description:
      - '&6Other &f- &7Make a report based off anything else'
      Importance: 0
      Item: anvil
    Anderes:
      Description:
      - '&6Anderes &f- &7mache einen Report für alle anderen Dinge'
      Importance: 0
      Item: anvil
```

**in config.yml:**
before:
```
Category:
  Enabled: true
  Categories:
    Griefing:
      Description:
      - '&6&m------&r &6&lReportsystem &8| &7Kathegorien &6&m------'
      Importance: 5
      Item: tnt
    Anderes:
      Description:
      - '&6Anderes &f- &7mache einen Report für alle anderen Dinge'
      Importance: 0
      Item: anvil
```
after reloading:
```
Category:
  Enabled: true
  Categories:
    Griefing:
      Description:
      - '&6&m------&r &6&lReportsystem &8| &7Kathegorien &6&m------'
      Importance: 5
      Item: tnt
    Other:
      Description:
      - '&6Other &f- &7Make a report based off anything else'
      Importance: 0
      Item: anvil
    Anderes:
      Description:
      - '&6Anderes &f- &7mache einen Report für alle anderen Dinge'
      Importance: 0
      Item: anvil
```

The missing once (from Default) got added with the Default entires

![image](https://user-images.githubusercontent.com/12080017/46281842-23a7ab00-c570-11e8-8359-9e11da863538.png)

Also menue said ...Slot 4, 6 and 6?....Well look at the Screens...
Arent These Slots 0,1 and 6??
